spring:
  # mysql
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/spring_example

    hikari:
      connection-timeout: 6000
      maximum-pool-size: 6


  redis:
    host: localhost
    port: 6379
