# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  # mysql
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/spring_example
    driver-class-name:  com.mysql.cj.jdbc.Driver

    hikari:
      connection-timeout: 6000
      maximum-pool-size: 6



  redis:
    host: localhost
    port: 6379
server:
  servlet:
    context-path: /api
